name: CI_stage
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '*'
      - '.github/**'

jobs:
  ci:
    uses: travelorrrka/ghaction-workflow-infracicd/.github/workflows/ci.yml@master
    # with:
    #   STAGING_ACCOUNT_ID: ${{ vars.STAGING_ACCOUNT_ID }}
    #   PRODUCTION_ACCOUNT_ID: ${{ vars.PRODUCTION_ACCOUNT_ID }}
    #   GHACTION_ROLE_NAME: ${{ vars.GHACTION_ROLE_NAME }}
    # secrets:
    #   APP_ID: ${{ secrets.APP_ID }}
    #   APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}